CREATE TABLE artists(
	ID INT PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	birth_date VARCHAR(50) NOT NULL,
	nationally VARCHAR(100) NOT NULL,
	style VARCHAR(75) NOT NULL
);
CREATE TABLE exhibts(
	ID INT PRIMARY KEY,
	artist_id INT,
	FOREIGN KEY(artist_id) REFERENCES artists(id)
	ON DELETE NO ACTION ON UPDATE NO ACTION,
	name VARCHAR(50) NOT NULL,
	description VARCHAR(100) NOT NULL,
	date_acquired VARCHAR(100) NOT NULL
);

CREATE TABLE exhibitCurators(
	ID INT PRIMARY KEY,
	exhibit_id INT,
	FOREIGN KEY(exhibit_id) REFERENCES exhibits(id)
	ON DELETE NO ACTION ON UPDATE NO ACTION,
	curator_id INT,
	FOREIGN KEY(curator_id) REFERENCES curators(id)
	ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE TABLE curators(
	ID INT PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	department VARCHAR(100) NOT NULL
);

CREATE TABLE exhibitlocations(
	ID INT PRIMARY KEY,
	exhibit_id INT,
	FOREIGN KEY(exhibit_id) REFERENCES exhibits(id)
	ON DELETE NO ACTION ON UPDATE NO ACTION,
	room_number VARCHAR(50) NOT NULL,
	floor VARCHAR(50) NOT NULL
);

CREATE TABLE exibitcollection(
	ID INT PRIMARY KEY,
	collection_id INT,
	FOREIGN KEY(collection_id) REFERENCES collections(id)
	ON DELETE NO ACTION ON UPDATE NO ACTION,
	exibit_id INT,
	FOREIGN KEY(exibit_id) REFERENCES exibits(id)
	ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE TABLE collections
	ID INT PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	description VARCHAR(50) NOT NULL
);

CREATE TABLE events(
	ID INT PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	date DATE NOT NULL,
	description VARCHAR(100) NOT NULL
);

CREATE TABLE visitors(
	ID INT PRIMERY KEY,
	name VARCHAR(50) NOT NULL,
	email VARCHAR(50) NOT NULL,
	membership_status VARCHAR(50) NOT NULL
);

CREATE TABLE tickets(
	ID INT PRIMERY KEY,
	visitor_id VARCHAR(50) NOT NULL,
	data_purchased VARCHAR(50) NOT NULL,
	price VARCHAR(50) NOT NULL
);